# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0d5ee0fcf565523d44559049c391eb1139854ec78dda04a81506cd0243fa13f93477f695b06c6dd5451cad15cad975d60e7da446cbaf1334af0717155563938

test:
  secret_key_base: 571cf095f417ef82974c2897f8eadbabc2fd50b44127facd47f9cec7a307e64da16936b0ca054c8745d4e1569ef4914f731133d7713781ebf1fe252ae02d0b9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
